name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Plugin
        run: bun run build:plugin

      - name: Run Linter
        run: bun run lint

      - name: Check Build
        run: |
          if [ ! -f "packages/plugin/dist/index.js" ]; then
            echo "Build failed - index.js not found"
            exit 1
          fi
          if [ ! -f "packages/plugin/dist/index.d.ts" ]; then
            echo "Build failed - index.d.ts not found"
            exit 1
          fi
          echo "Build verification passed" 